<?php

/**
 * Generate ACF Field repeater with three level
 * Repeater field with: Title and Subtitle
 */
function repeaterWithThreeLevels($prefix1, $prefix2, $prefix3, $uniqueId1, $uniqueId2, $uniqueId3, $uniqueId4, $uniqueId5, $uniqueId6, $uniqueId7, $uniqueId8, $uniqueId9) {
  return
    array(
      array (
        'key' => 'field_' . $uniqueId1,
        'label' => 'Lista de Itens',
        'name' => $prefix1 . '_list',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => 'field_' . $uniqueId2,
        'min' => '',
        'max' => '',
        'layout' => 'block',
        'button_label' => 'Adicionar Item',
        'sub_fields' => array (
          array (
            'key' => 'field_' . $uniqueId2,
            'label' => 'Pergunta',
            'name' => $prefix1 . '_list_item_title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => '',
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
          ),
          array (
            'key' => 'field_' . $uniqueId3,
            'label' => 'Resposta',
            'name' => $prefix1 . '_list_item_editor',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
          ),
          array (
            'key' => 'field_' . $uniqueId4,
            'label' => 'Sub-Item',
            'name' => $prefix2 . '_list',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'collapsed' => 'field_' . $uniqueId5,
            'min' => '',
            'max' => '',
            'layout' => 'block',
            'button_label' => 'Adicionar Subitem',
            'sub_fields' => array (
              array (
                'key' => 'field_' . $uniqueId5,
                'label' => 'Pergunta',
                'name' => $prefix2 . '_list_item_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => '',
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'field_' . $uniqueId6,
                'label' => 'Resposta',
                'name' => $prefix2 . '_list_item_editor',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
              ),
              array (
                'key' => 'field_' . $uniqueId7,
                'label' => 'Sub-Sub-Item',
                'name' => $prefix3 . '_list',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => 'field_' . $uniqueId8,
                'min' => '',
                'max' => '',
                'layout' => 'block',
                'button_label' => 'Adicionar SubSubitem',
                'sub_fields' => array (
                  array (
                    'key' => 'field_' . $uniqueId8,
                    'label' => 'Pergunta',
                    'name' => $prefix3 . '_list_item_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => '',
                    'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                  ),
                  array (
                    'key' => 'field_' . $uniqueId9,
                    'label' => 'Resposta',
                    'name' => $prefix3 . '_list_item_editor',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
}
