<?php

/**
 * Repeater of features lists
 */
function repeaterOfLists( $prefix, $uniqueId, $uniqueId1, $uniqueId2, $uniqueId3, $uniqueId4, $uniqueId5, $repeater_label = 'Grupo de Listas', $max_items = null ) {
  return
    array(
      array (
        'key' => 'field_' . $uniqueId,
        'label' => $repeater_label,
        'name' => $prefix . '_list',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => 'field_' . $uniqueId2,
        'min' => '',
        'max' => $max_items,
        'layout' => 'block',
        'button_label' => 'Adicionar Lista',
        'sub_fields' => array (
          array (
            'key' => 'field_' . $uniqueId1,
            'label' => 'Imagem de fundo',
            'name' => $prefix . '_list_item_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 30,
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,png,svg',
          ),
          array (
            'key' => 'field_' . $uniqueId2,
            'label' => 'Título',
            'name' => $prefix . '_list_item_title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => 50,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
          ),
          array (
            'key' => 'field_' . $uniqueId3,
            'label' => 'Tipo de Lista',
            'name' => $prefix . '_list_item_type',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => '',
            'wrapper' => array (
              'width' => 20,
              'class' => '',
              'id' => '',
            ),
            'choices' => array (
              'desafio' => 'Desafio',
              'solucao' => 'Solução',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
          ),
          array (
            'key' => 'field_' . $uniqueId4,
            'label' => 'Desafios e soluções',
            'name' => $prefix . '_list_item_sublist',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'collapsed' => 'field_' . $uniqueId5,
            'min' => '',
            'max' => '',
            'layout' => 'row',
            'button_label' => 'Adicionar Item à lista',
            'sub_fields' => array (
              array (
                'key' => 'field_' . $uniqueId5,
                'label' => 'Título do Item',
                'name' => $prefix . '_list_item_sublist_item_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => 50,
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
            ),
          ),
        ),
      ),
    );
}